
# Data & preprocessing
data_path: "/tmp/cellNiche_c/data/Atlas1_filtered"
dataset: "well06_cellTypt"
embedding_type: "pheno_expr"
hvg: true

# Graph construction
k_neighborhood: 20
radius: null

# Sampling & training
batch_size: 1024
epochs: 2
max_steps: 80
max_duration: 60      # in minutes
lr: 0.001
weight_decay: 0.0
dropout: 0.0

# Model architecture
hidden_channels: [512, 256]
size: [10, 10]
projection: [128, 64]
decoder: [64]

# Contrastive strategy
tau: 0.9
ns: 0.5
strategy: "freq"
use_weight: true
pos_weight_strategy: "inverse_sim"
neg_weight_strategy: "inverse_sim"

# Random‐walk
wt: 10
wl: 4
p: 0.25
q: 4.0

# Misc
seed: 2189
save: true
metrics: true
save_path: "/tmp/cellNiche_c/results"
verbose: true
