# Data & preprocessing
data_path: "/share/home/liangzhongming/phd_code/530/CellNiche/data/"
dataset: "well06_cellTypt"
phenoLabels: "supertype"
nicheLabels: "Sub_molecular_tissue_region" # None
embedding_type: "pheno_expr"
hvg: False

# Graph construction
k_neighborhood: null
radius: 300.0

# Sampling & training
batch_size: 1024  # 2048  影响训练时间
epochs: 1
max_steps: null
lr: 0.001
weight_decay: 0.0
dropout: 0.0

# Model architecture
hidden_channels: [512, 256]
size: [10, 10]
projection: "" # [128, 64]
decoder: "" # [64]

# Contrastive strategy
tau: 0.9
negative_slope: 0.5
strategy: "freq"
use_weight: False
pos_weight_strategy: "inverse_sim"
neg_weight_strategy: "inverse_sim"

# Random‐walk
wt: 10
wl: 4
p: 0.25
q: 4.0

# Misc
seed: 1843
save: False
metrics: true
refine: False
save_path: "/share/home/liangzhongming/phd_code/530/CellNiche/results"
verbose: true